Better Password Security [WIP]
rustbridge/rustbridge.io pull request #51
Opened 2018-03-24 02:39 UTC by technetos

:radioactive: :skull_and_crossbones: [WIP] Do Not Merge :skull_and_crossbones: :radioactive:

2018-03-27 16:52 UTC, rupsis requested changes
The code looks great, but we need to have the proper steps in the README to generate a salt, and add users to the database via the CLI tool.

2018-03-30 20:45 UTC, technetos commented
Adding users has been handled and documented.

2018-03-30 21:04 UTC, rupsis approved these changes

2018-03-31 08:11 UTC, ghost approved these changes

2018-03-31 15:27 UTC, merged